name: SSHX Fetch

on: [push, workflow_dispatch]

jobs:
  fetch_sshx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSHX script
        run: curl -sSf https://sshx.io/get | sh -s run

      - name: Ensure storage folder exists
        run: mkdir -p storage

      - name: Move all generated files to storage
        run: mv * storage/ || true

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add storage
          git commit -m "Updated storage with new SSHX files" || true
          git push
