on: [push, workflow_dispatch]

jobs:
  fetch_sshx:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/$GITHUB_REPOSITORY.git

      - name: Run SSHX script
        run: curl -sSf https://sshx.io/get | sh -s run
